exports.stateActionList = [
	'Maharashtra',
	'Delhi',
	'Tamil Nadu',
	'Rajasthan',
	'Madhya Pradesh',
	'Uttar Pradesh',
	'Gujarat',
	'Telangana',
	'Andhra Pradesh',
	'Kerala',
	'Jammu and Kashmir',
	'Karnataka',
	'Haryana',
	'West Bengal',
	'Punjab',
	'Bihar',
	'Odisha',
	'Uttarakhand',
	'Chhattisgarh',
	'Himachal Pradesh',
	'Assam',
	'Jharkhand',
	'Chandigarh',
	'Ladakh',
	'Andaman and Nicobar Islands',
	'Goa',
	'Puducherry',
	'Manipur',
	'Tripura',
	'Mizoram',
	'Arunachal Pradesh',
	'Dadra and Nagar Haveli',
	'Nagaland',
	'Meghalaya',
	'Daman and Diu',
	'Lakshadweep',
	'Sikkim'
];